spring:
  messages:
    basename: messages
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mode: DEVELOPMENT
  devtools:
    restart:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liHJcnC9pXwRxaPS
            client-secret: ${GITHUB_SECRET:}
            scope: user:email
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${my_pass:}
    username: ${my_username:root}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/collaboration-app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
remember_me_key: ${remembermekey}
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE

        SQL: TRACE
      nodeValue: WARN
    blog: WARN
server:
  port: 8080
mail:
  platformEmail: "e-platform-stuttgart@gmail.com"
  host: ${MAILHOG_HOST:localhost}
  port: ${MAILHOG_PORT:1025}
  username: ${MAIL_USER}
  password: ${MAIL_PASSWORD}

cloudinary :
  cloud_name : ${CLOUDINARY_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret : ${CLOUDINARY_API_SECRET}

google.recaptcha:
  site: ${RECAPTCHA_SITE_KEY:test}
  secret: ${RECAPTCHA_SITE_SECRET:test}
